typography_spectrum: 0.5308862887322903
color:
  brandStrength: 0.02272662566974759
  lightness: 0.7937391982413828
  saturation: 0.9886097344569862
  rhythmicContrast: 0.7067344072274864
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.683385840151459
author:
  name: Catherine Kirchner
  email: ckirchner@stmaryscatholicschool.net
  url: www.stmaryscatholicschool.net
name: St. Mary's Knights - Montana
navigation:
  - name: Ascend
    url: 'https://stmaryscatholicschool.ascendsms.com/default.aspx'
    type: external
  - name: FACTS
    url: 'https://online.factsmgt.com/SignIn.aspx?ReturnUrl=%2f'
    type: external
